### ISSUE TITLE
Stopped Working At All

### ISSUE THREAD

**Issue by zethon** [johnpapa/vscode-peacock#516]
**Versions (please complete the following information):**

- OS: mac
- VS Code version 1.76
- Peacock Version 4.2.2

**Describe the bug**
Colors don't change anymore. If I open a project that already had a specific color, the project stays that color, even if I uninstall the plugin. Reinstalling did not help. Restarting VSCode did not help. 

**To Reproduce**

Simply install Peacock on the latest VSCode and it does not work.

**Expected behavior**
The plugin should work

**Screenshots**
I can provide video if necessary.

**Additional context**
None

**Comment by johnpapa** [comment]
Thank you @zethon for creating this issue!

**Comment by zethon** [comment]
On multiple computers the plugin no longer works. :(

**Comment by kiranFullStack** [comment]
I wish it just stopped working on my VS Code....because it is permanently set to s stupid green color 😡😡😡😡

**Comment by kiranFullStack** [comment]
I had to remove all colors in settings, then it got reset

**Comment by Pfeil** [comment]
Same issue here. Removing the colors from .vscode/settings.json is easy, but if I try to select a color, the list of colors will simply not appear. All other Peacock items in the menu will also not work.

The only reaction I see from selection a Peacock command, is the "Activating Extensions" spinner in the status bar. I would guess that there is an initialization issue, but I have no idea how to debug this properly.

OS: MacOS 13.2.1
VScode: 1.76.2
Peacock: v4.2.2

**Comment by jamiehs** [comment]
I'm also getting the issue of having a non-functional Peacock extension.
I'm on:
* MacOS: 12.6.3
* VSCode: 1.77.0
* Peacock: 4.2.2

![image](https://user-images.githubusercontent.com/66539/228974160-6c3d1167-8833-491d-902b-51833f9abb11.png)

Runtime Status says:
>Not yet activated.

Peacock items are still in the command palette, activating them sometimes shows "Activating Extensions..." at the bottom status bar as @Pfeil stated, however the colors are not applied. Existing color themes persist obviously as they are already written to the `.vscode/settings.json` file.

I have tried saving a workspace explicitly instead of relying on the `.vscode/settings.json` file, but it makes no difference.

I have also tried deactivating, reactivating, uninstalling, and reinstalling. None of these work.

**Comment by zethon** [comment]
For anyone else seeing this problem -- when I upgraded to VSCode 1.77, Peacock started working again.

**Comment by jamiehs** [comment]
Unfortunately I'm on VSCode 1.77.0 and am still seeing this issue.

**Comment by migbash** [comment]
Same here, just installed the extension on `1.77.0` and none of the commands work and no change is visible.

**Comment by weaversam8** [comment]
Sam here, `1.77.1` doesn't seem to improve it either.

**Comment by jamiehs** [comment]
How many of us have the LiveShare extension installed?
https://github.com/johnpapa/vscode-peacock/issues/511#issuecomment-1418558097

Disabling LiveShare also fixed this for me. It appears that this is likely not an issue with Peacock, or a conflict with the LiveShare extension. (in my case)

**Comment by athos** [comment]
Wow, disabling LiveShare works for me too.

**Comment by jgbpercy** [comment]
Yep issue was LiveShare for me as well, weird

**Comment by samo9789** [comment]
I am glad I found this post, it was the same for me, Live Share was keeping Peacock from working. Hopefully this can be sorted out and I can re-enable Live Share in the future

Thanks to the developers for this extension

**Comment by hedgeye-smarshall** [comment]
Disabling LiveShare worked for me as well. Randomly started happening this week.

**Comment by anotherlab** [comment]
It stopped working for me some time ago for new workspaces, works fine in older ones and I do not have Live Share installed
VS Code 1.81.0
Windows 11

If I edit the.code-workspace file and copy the settings from an older one with the folders path defined, it appears to work.

**Comment by guimar86** [comment]
I don't have liveShare yet I still have the same issue as everyone mentioned previously:

- Installed Peacock
- Changed colors for a few editor windows
- Used the option to brighten and darken some of the colors
- Uninstalled

When I uninstalled the green still remained. Installed again and tried the "**reset workspace colors** " option but no change takes place, the green still remains.

@johnpapa is there a way to know which extensions could possible have conflicts so we try and disable like other people did with liveshare?

![image](https://github.com/johnpapa/vscode-peacock/assets/10280591/8fa98bfa-7850-4ab9-a124-d10dacfb6bad)

**Comment by guimar86** [comment]
## Profile 
Hey guys, while we wait for a definitive solution I found out that using a different profile in vscode completely removes the colors set by peacock as its literally a new window. You however need to re-install all plugins you need for your development.

### Official documentation
https://code.visualstudio.com/docs/editor/profiles

### Vscode official youtube page
https://www.youtube.com/watch?v=QjvvqR9KyVo

**Comment by gerhardvr-finclude** [comment]
Had this issue with Peacock for a while now. Running on Windows using VSCode insiders. Disabling Live Share immediately resolved the Peacock issue for me.

Version: 1.83.0-insider (user setup)
Commit: 7b0ae6cf9d5a0c891ad1adc4da9c36c4dc453d4d
Date: 2023-09-14T05:33:44.297Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by carlocardella** [comment]
@guimar86 slight OT but it depends on how you create a new profile, you can choose to "inherit" settings and extensions from `Default` or start fresh.

[Partial profiles](https://code.visualstudio.com/docs/editor/profiles#_partial-profile)

**Comment by nader-khiari** [comment]
I had the same issue myself and I believe it has a conflict with [Live share](https://visualstudio.microsoft.com/services/live-share/) plugin.
Try reinstalling Live Share and I think it would work fine. It worked for me anyway.

**Comment by sijakret** [comment]
> I had the same issue myself and I believe it has a conflict with [Live share](https://visualstudio.microsoft.com/services/live-share/) plugin. Try reinstalling Live Share and I think it would work fine. It worked for me anyway.

disabling live share extension solved it for me

**Comment by tharindu-nw** [comment]
I am on vscode 1.96
Got this issue and was resolved when Liveshare was disabled

**Comment by Arush267** [comment]
> I wish it just stopped working on my VS Code....because it is permanently set to s stupid green color 😡😡😡😡

Same pls tell if you know how to fix it cuz it looks dreadful and doesnt get removed even if i uninstall or restart

**Comment by carlocardella** [comment]
> > I wish it just stopped working on my VS Code....because it is permanently set to s stupid green color 😡😡😡😡
> 
> Same pls tell if you know how to fix it cuz it looks dreadful and doesnt get removed even if i uninstall or restart

Go to `Settings` and reset `Peacock: Color` (the setting id is `peacock.color`)

![Image](https://github.com/user-attachments/assets/bb6344dc-8e97-4106-b2ab-099ff0bf3656)

**Comment by johnpapa** [comment]
Thank you for reporting this — the engagement here tells us it affects multiple users. To help investigate on current versions, could anyone still experiencing this please provide:
- **Current VS Code version**
- **Current Peacock version**
- Contents of your `.vscode/settings.json`
- Output from the Peacock output channel (View → Output → select "Peacock")

This will help determine if the issue persists on newer VS Code versions or was resolved.

**Comment by johnpapa** [comment]
Closing — this issue has been open since 2023 with extensive discussion but no recent activity. If Peacock still isn't working on v4.2.4, please open a new issue with your VS Code version, OS, and the Output panel (Peacock channel) logs. Thanks for the detailed reports! 🙏
